# Generated by Django 4.2 on 2023-04-26 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_mobile_number_address_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceLine',
        ),
    ]
