# Generated by Django 4.2 on 2023-04-26 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='image2',
        ),
    ]
