# Generated by Django 4.2 on 2023-04-25 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_service_service_name_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='mobile_number',
            new_name='mobile',
        ),
    ]
