# Generated by Django 4.2 on 2023-05-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_serviceinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceinfo',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
