# Generated by Django 4.2 on 2023-05-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_serviceinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
