# Generated by Django 4.2.1 on 2023-05-14 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_delete_invoice_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Serviceinfo',
        ),
    ]
